# Generated by Django 2.2.3 on 2019-07-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190725_2045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='favoritething',
            table='favorite_thing',
        ),
    ]
