# Generated by Django 2.2.3 on 2019-07-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190725_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritething',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_things', to='main.Category'),
        ),
    ]
