# Generated by Django 2.2.3 on 2019-07-30 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190728_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritething',
            name='ranking',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
