# Generated by Django 2.2.3 on 2019-08-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190801_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritething',
            name='audit_logs',
        ),
        migrations.RemoveField(
            model_name='historicalfavoritething',
            name='audit_logs',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
