# Generated by Django 2.2.3 on 2019-08-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190816_1153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalfavoritething',
            table='favorite_things_history',
        ),
    ]
